#!/usr/bin/env python3
"""Generate c-arena/: a Makefile-driven compile arena for every C sample.

- harness/<task>.c   : the hidden test driver (with main()) for each eval task
- samples/*.c        : all dumped model failure samples + referee solutions
                       (referee files are the positive controls: they must all pass)
- Makefile           : `make` compiles everything (never stops on errors),
                       `make check` runs the binaries and prints a result table,
                       `make summary` aggregates pass/fail per model.

Regenerate after new eval runs:  .venv/bin/python scripts/gen_arena.py
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from eval_code import TASKS  # noqa: E402

ARENA = ROOT / "c-arena"
HARNESS = ARENA / "harness"
SAMPLES = ARENA / "samples"

TASK_NAMES = sorted(t["name"] for t in TASKS)


def task_of(stem: str) -> str | None:
    """Extract task name from '<model>-<task>-t<N>' or 'referee-<task>'."""
    m = re.search(r"-([a-z0-9_]+)-t\d+$", stem)
    cand = m.group(1) if m else stem.removeprefix("referee-")
    return cand if cand in TASK_NAMES else None


def main() -> None:
    HARNESS.mkdir(parents=True, exist_ok=True)
    SAMPLES.mkdir(parents=True, exist_ok=True)

    # 1. harnesses
    for t in TASKS:
        (HARNESS / f"{t['name']}.c").write_text(t["test"] + "\n")

    # 2. samples: failure dumps + referee solutions (positive controls)
    for old in SAMPLES.glob("*.c"):
        old.unlink()
    skipped = []
    for f in sorted((ROOT / "results" / "failures").glob("*.c")):
        if task_of(f.stem):
            shutil.copy(f, SAMPLES / f.name)
        else:
            skipped.append(f.name)
    for f in sorted((ROOT / "results" / "referee" / "kimi-k3").glob("*.c")):
        shutil.copy(f, SAMPLES / f"referee-{f.name}")
    if skipped:
        print("skipped (no task match):", ", ".join(skipped))

    # 3. Makefile with one rule per sample
    rules, bins = [], []
    for s in sorted(SAMPLES.glob("*.c")):
        task = task_of(s.stem)
        if not task:
            continue
        b = f"build/{s.stem}"
        bins.append(b)
        rules.append(
            f"{b}: samples/{s.stem}.c harness/{task}.c\n"
            f"\t@mkdir -p build\n"
            f"\t@rm -f $@.COMPILE_FAIL\n"
            f"\t@$(CC) $(CFLAGS) -o $@ $^ 2> $@.log || touch $@.COMPILE_FAIL\n"
        )
    makefile = f"""# Auto-generated by scripts/gen_arena.py — do not edit by hand.
# Usage:
#   make          compile every sample (never stops on errors)
#   make check    compile, run all binaries, print per-sample results
#   make summary  per-model aggregate
#   make clean
CC ?= cc
CFLAGS := -std=c11 -Wall -O1
BINS := {' '.join(bins)}

all: $(BINS)

{chr(10).join(rules)}
check: all
\t@.venv-check 2>/dev/null || true
\t@python3 summarize.py

summary: check

clean:
\trm -rf build

.PHONY: all check summary clean
"""
    (ARENA / "Makefile").write_text(makefile)

    # 4. summarizer
    (ARENA / "summarize.py").write_text(f'''#!/usr/bin/env python3
"""Print per-sample and per-model results for the c-arena build."""
import subprocess
from collections import defaultdict
from pathlib import Path

TASKS = {TASK_NAMES!r}

def parse(stem):
    if stem.startswith("referee-"):
        return "referee", stem.removeprefix("referee-"), "-"
    base, _, trial = stem.rpartition("-t")
    for t in TASKS:
        if base.endswith("-" + t):
            return base[: -len(t) - 1], t, trial
    return base, "?", trial

SAMPLES = sorted(Path("samples").glob("*.c"))
rows = []
agg = defaultdict(lambda: [0, 0, 0])  # model -> [pass, test_fail, compile_fail]
for s in SAMPLES:
    stem = s.stem
    b = Path("build") / stem
    if Path(str(b) + ".COMPILE_FAIL").exists():
        result = "COMPILE FAIL"
    elif b.exists():
        r = subprocess.run([str(b)], capture_output=True, timeout=10)
        result = "PASS" if r.returncode == 0 else "TEST FAIL"
    else:
        result = "COMPILE FAIL"
    model, task, trial = parse(stem)
    rows.append((model, task, trial, result))
    agg[model][{{"PASS": 0, "TEST FAIL": 1, "COMPILE FAIL": 2}}[result]] += 1

print(f"{{'model':<16}} {{'task':<16}} {{'t':<3}} result")
print("-" * 50)
for model, task, trial, result in rows:
    print(f"{{model:<16}} {{task:<16}} {{trial:<3}} {{result}}")
print()
print(f"{{'model':<16}} {{'pass':>5}} {{'test-fail':>9}} {{'compile-fail':>12}}")
print("-" * 46)
for model in sorted(agg):
    p, tf, cf = agg[model]
    print(f"{{model:<16}} {{p:>5}} {{tf:>9}} {{cf:>12}}")
''')
    print(f"arena: {len(list(HARNESS.glob('*.c')))} harnesses, "
          f"{len(list(SAMPLES.glob('*.c')))} samples -> {ARENA}")


if __name__ == "__main__":
    main()
